In [1]:
import tensorflow as tf

# Create Zeros Tesnor using tf.zeros_initializer()

##### Initializer that generates tensors initialized to 0.

##### Initializers allow you to pre-specify an initialization strategy, encoded in the Initializer object, without knowing the shape and dtype of the variable being initialized.
##### Syntax: tf.zeros_initializer()

In [7]:
def zeros_variable(shape, dtype, initializer):
    return tf.Variable(initializer(shape = shape , dtype = dtype))

In [9]:
zeros_init_tf_var = zeros_variable((2,2), tf.float32, tf.zeros_initializer())  # tf.zeros_initializer()
zeros_init_tf_var

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

In [11]:
zeros_variable((3,2,5), tf.int32, tf.zeros_initializer())


<tf.Variable 'Variable:0' shape=(3, 2, 5) dtype=int32, numpy=
array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]])>

In [12]:
zeros_variable((3,2,5), tf.bool, tf.zeros_initializer())


<tf.Variable 'Variable:0' shape=(3, 2, 5) dtype=bool, numpy=
array([[[False, False, False, False, False],
        [False, False, False, False, False]],

       [[False, False, False, False, False],
        [False, False, False, False, False]],

       [[False, False, False, False, False],
        [False, False, False, False, False]]])>

In [14]:
tf.Variable(tf.zeros_initializer()((2,2), tf.float32))  # working in single line 

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>