In [1]:
# Importing library 
import tensorflow as tf

In [3]:
# Syntax (sparse_tensor):
# tf.sparse.SparseTensor(indices, values, dense_shape)
# values: A 1D tensor with shape [N] containing all nonzero values.
# indices: A 2D tensor with shape [N, rank], containing the indices of the nonzero values.
# dense_shape: A 1D tensor with shape [rank], specifying the shape of the tensor.

# Creating tensorflow Sparse Tensor

In [7]:
sp_tf1 = tf.SparseTensor(indices = [[0,2],[1,4]], values = [10,20], dense_shape = [2,10])
print(sp_tf1)

SparseTensor(indices=tf.Tensor(
[[0 2]
 [1 4]], shape=(2, 2), dtype=int64), values=tf.Tensor([10 20], shape=(2,), dtype=int32), dense_shape=tf.Tensor([ 2 10], shape=(2,), dtype=int64))


# Create sparse tensor from dense 

In [9]:
import numpy as np 

In [13]:
arr = np.array([[1,0,1,0],[1,2,1,0],[2,1,0,0], [0,0,3,0]])
arr

array([[1, 0, 1, 0],
       [1, 2, 1, 0],
       [2, 1, 0, 0],
       [0, 0, 3, 0]])

In [15]:
sp_tf_from_dense = tf.sparse.from_dense(arr)
print(sp_tf_from_dense)

SparseTensor(indices=tf.Tensor(
[[0 0]
 [0 2]
 [1 0]
 [1 1]
 [1 2]
 [2 0]
 [2 1]
 [3 2]], shape=(8, 2), dtype=int64), values=tf.Tensor([1 1 1 2 1 2 1 3], shape=(8,), dtype=int32), dense_shape=tf.Tensor([4 4], shape=(2,), dtype=int64))


In [19]:
# Extract values, indices and shape of tensor

values_np =sp_tf_from_dense.values.numpy()
print(values_np)

[1 1 1 2 1 2 1 3]


In [22]:
values_lists = sp_tf_from_dense.values.numpy().tolist()
print(values_lists)

[1, 1, 1, 2, 1, 2, 1, 3]


In [30]:
indices_vals = sp_tf_from_dense.indices.numpy()
print(indices_vals)

[[0 0]
 [0 2]
 [1 0]
 [1 1]
 [1 2]
 [2 0]
 [2 1]
 [3 2]]


In [29]:
indices_vals_lists = sp_tf_from_dense.indices.numpy().tolist()  # in list format
print(indices_vals_lists)

[[0, 0], [0, 2], [1, 0], [1, 1], [1, 2], [2, 0], [2, 1], [3, 2]]


In [33]:
size_of_metrics = sp_tf_from_dense.dense_shape.numpy()
size_of_metrics

array([4, 4], dtype=int64)

#  Sparse tensor to Dense

In [39]:
dt_from_sparse = tf.sparse.to_dense(sp_tf_from_dense)
print(dt_from_sparse)

tf.Tensor(
[[1 0 1 0]
 [1 2 1 0]
 [2 1 0 0]
 [0 0 3 0]], shape=(4, 4), dtype=int32)


In [41]:
dt_from_sparse.numpy()   # Converting dt to numpy

array([[1, 0, 1, 0],
       [1, 2, 1, 0],
       [2, 1, 0, 0],
       [0, 0, 3, 0]])

#  Applying mathematical operation on Sparse Tensor 

In [49]:
sp_tf_add = tf.sparse.add(sp_tf_from_dense,sp_tf_from_dense)
print(sp_tf_add)

SparseTensor(indices=tf.Tensor(
[[0 0]
 [0 2]
 [1 0]
 [1 1]
 [1 2]
 [2 0]
 [2 1]
 [3 2]], shape=(8, 2), dtype=int64), values=tf.Tensor([2 2 2 4 2 4 2 6], shape=(8,), dtype=int32), dense_shape=tf.Tensor([4 4], shape=(2,), dtype=int64))


In [52]:
added_sparse = tf.sparse.to_dense(sp_tf_add).numpy()
print(added_sparse)

[[2 0 2 0]
 [2 4 2 0]
 [4 2 0 0]
 [0 0 6 0]]


In [53]:
added_sparse_in_list = tf.sparse.to_dense(sp_tf_add).numpy().tolist()
print(added_sparse_in_list)

[[2, 0, 2, 0], [2, 4, 2, 0], [4, 2, 0, 0], [0, 0, 6, 0]]
