In [1]:
import tensorflow as tf

### Initializer that generates tensors initialized to 1.

### Initializers allow you to pre-specify an initialization strategy, encoded in the Initializer object,
### without knowing the shape and dtype of the variable being initialized.

# Create Ones Tesnor using tf.ones_initializer()

In [3]:
# Syntax:
# tf.ones_initializer()

In [4]:
def ones_variable(shape, dtype, initializer):
    return tf.Variable(initializer(shape = shape, dtype = dtype))

In [7]:
ones_variable((2,2), tf.float32,tf.ones_initializer())

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [8]:
ones_variable((3,3), tf.float32,tf.ones_initializer())

<tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [10]:
ones_variable((5,4), tf.int32,tf.ones_initializer())

<tf.Variable 'Variable:0' shape=(5, 4) dtype=int32, numpy=
array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])>

In [13]:
# 3D tensor
ones_variable_3d = ones_variable((2, 3, 4), tf.float32, tf.ones_initializer())
print( ones_variable_3d)


<tf.Variable 'Variable:0' shape=(2, 3, 4) dtype=float32, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)>


In [14]:
# 4D tensor
ones_variable_4d = ones_variable((1, 2, 3, 4), tf.float32, tf.ones_initializer())
print(ones_variable_4d)


<tf.Variable 'Variable:0' shape=(1, 2, 3, 4) dtype=float32, numpy=
array([[[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]]], dtype=float32)>
