In [11]:
import tensorflow as tf

In [12]:
# syntax: tf.ones(shape, dtype=tf.dtypes.float32, name=None) -> Return Ones Tensor

# Creates a tensor with all elements set to (1)

In [13]:
tf.ones((1), tf.float64)   # by-deflult ---> dtype = float32

<tf.Tensor: shape=(1,), dtype=float64, numpy=array([1.])>

In [14]:
ones_2d_tensor =  tf.ones((2,2), tf.int32, name = "2-D tensor Demo")
print(ones_2d_tensor)

tf.Tensor(
[[1 1]
 [1 1]], shape=(2, 2), dtype=int32)


In [15]:
ones_3d_tensor = tf.ones((2,2,4), tf.int64)
print(ones_3d_tensor)

tf.Tensor(
[[[1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]]], shape=(2, 2, 4), dtype=int64)


In [16]:
ones_4d_tensor = tf.ones((3, 2, 2, 2))
print("4D Tensor with ones (float32):")
print(ones_4d_tensor)


4D Tensor with ones (float32):
tf.Tensor(
[[[[1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]]]


 [[[1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]]]


 [[[1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]]]], shape=(3, 2, 2, 2), dtype=float32)
