In [7]:
import tensorflow as tf

#  Creates a tensor of all ones that has the same shape as the output

In [8]:
# syntax: 	
# tf.ones_like(input, dtype=None, name=None) -> Return Ones Tensor


In [9]:
const_2d_tensor = tf.constant([[1,2,3], [4,5,6]])

In [10]:
ones_2d_from_const = tf.ones_like(const_2d_tensor, tf.float32)
print(ones_2d_from_const)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [12]:
var_2d_tensor = tf.Variable([[1, 2, 3], [4, 5, 6]])

In [13]:
ones_2d_from_variable = tf.ones_like(var_2d_tensor)   # by default ---> int32
print(ones_2d_from_variable)

tf.Tensor(
[[1 1 1]
 [1 1 1]], shape=(2, 3), dtype=int32)


#  3d tensor

In [14]:
const_3d_tensor = tf.constant([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

ones_3d_from_const = tf.ones_like(const_3d_tensor, tf.float32)
print("3D tensor from constant:\n", ones_3d_from_const)

3D tensor from constant:
 tf.Tensor(
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]], shape=(2, 2, 2), dtype=float32)


#  4d tensor 

In [15]:
const_4d_tensor = tf.constant([[[[1, 2], [3, 4]], [[5, 6], [7, 8]]]])
ones_4d_from_const = tf.ones_like(const_4d_tensor, tf.float32)

print("4D tensor from constant:\n", ones_4d_from_const)


4D tensor from constant:
 tf.Tensor(
[[[[1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]]]], shape=(1, 2, 2, 2), dtype=float32)


#  using List

In [16]:
list_2d = [[1, 2, 3], [4, 5, 6]]
tensor_from_list = tf.constant(list_2d)

In [17]:
ones_2d_from_list = tf.ones_like(tensor_from_list)
print("2D tensor from list:\n", ones_2d_from_list)


2D tensor from list:
 tf.Tensor(
[[1 1 1]
 [1 1 1]], shape=(2, 3), dtype=int32)


# Using tuple

In [18]:
tuple_2d = ([1, 2, 3], [4, 5, 6])
tensor_from_tuple = tf.constant(tuple_2d)

In [19]:
ones_2d_from_tuple = tf.ones_like(tensor_from_tuple)

print("2D tensor from tuple:\n", ones_2d_from_tuple)

2D tensor from tuple:
 tf.Tensor(
[[1 1 1]
 [1 1 1]], shape=(2, 3), dtype=int32)


#  Using numpy array

In [20]:
import numpy as np 

numpy_array = np.array([[1, 2, 3], [4, 5, 6]])


In [22]:
tensor_from_numpy = tf.constant(numpy_array)
ones_2d_from_numpy = tf.ones_like(tensor_from_numpy)

print("2D tensor from numpy array:\n", ones_2d_from_numpy)

2D tensor from numpy array:
 tf.Tensor(
[[1 1 1]
 [1 1 1]], shape=(2, 3), dtype=int32)
