In [1]:
import tensorflow as tf

# Create Zeros Tesnor using tf.zeros()

#### Creates a tensor with all elements set to zero (0)

#### Syntax: tf.zeros(shape, dtype=tf.dtypes.float32, name=None) -> Return ZerosTensor

In [4]:
zeros_2d_tensor = tf.zeros((2,2), dtype = tf.int32)
print(zeros_2d_tensor)

tf.Tensor(
[[0 0]
 [0 0]], shape=(2, 2), dtype=int32)


In [5]:
zeros_3d_tensor = tf.zeros((2,2,4), dtype = tf.int8)   # Creating 3-d Tensor
print(zeros_3d_tensor)

tf.Tensor(
[[[0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]]], shape=(2, 2, 4), dtype=int8)


In [6]:
zeros_3d_tensor = tf.zeros((2,2,4), dtype = tf.float32)   # Creating 3-d Tensor
print(zeros_3d_tensor)

tf.Tensor(
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]], shape=(2, 2, 4), dtype=float32)


In [7]:
zeros_3d_tensor.shape

TensorShape([2, 2, 4])

In [8]:
zeros_3d_tensor.dtype

tf.float32

In [9]:
zeros_3d_tensor.numpy()

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)

In [11]:
zeros_3d_tensor.numpy().tolist()

[[[0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0]],
 [[0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0]]]

In [13]:
# Creating a 4D tensor of shape (2, 3, 4, 5) filled with zeros
tensor_4d = tf.zeros((2, 3, 4, 5))
print(tensor_4d)

tf.Tensor(
[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]], shape=(2, 3, 4, 5), dtype=float32)


In [14]:
# Dynamic shape based on some conditions or calculations
batch_size = 4
height = 2
width = 3

tensor_dynamic_shape = tf.zeros((batch_size, height, width))
print("Tensor with dynamic shape:")
print(tensor_dynamic_shape)

Tensor with dynamic shape:
tf.Tensor(
[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]], shape=(4, 2, 3), dtype=float32)
