In [3]:
import tensorflow as tf 
import numpy as np

# Syntax: tf.add(x, y, name=None)

### Scaler adding

In [13]:
x= 10.25
y = 20

add = tf.add(x,y,name ='scaler adding')   # name is optional
# add
print(f"Added Value is {add}. ")

Added Value is 30.25. 


### Adding lists 

In [18]:
ls1 = [1,2,3,4]
ls2 = [5,6,7,8]

added_ls = tf.add(ls1,ls2)
added_ls

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 6,  8, 10, 12])>

### Adding tuples

In [19]:
tup1 = (1,2,3,4)
tup2 = (5,6,7,8)

added_tupls = tf.add(tup1, tup2)
added_tupls

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 6,  8, 10, 12])>

### Adding list/tuples with scaler

In [38]:
ls = [1,2,3,4]
x = 10

add = tf.add(ls,x)
add

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([11, 12, 13, 14])>

In [23]:
tupls = (1,2,3,4)
x = 20

add = tf.add(tupls,x)
add

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([21, 22, 23, 24])>

## Adding 2 list/tuples with different size

#### ls1 = [1,2,3,4]
#### ls2 = [5,6]

#### add = tf.add(ls1,ls2)

### Note:
#### If the size of 2 variables is different then tf.add() function will through error.
#### If any one of the variables contains only a single item then it will do the element-wise operation.




###### Output:
###### ...
###### ...
###### ...
###### InvalidArgumentError: {{function_node __wrapped__AddV2_device_/job:localhost/replica:0/task:0/device:CPU:0}} Incompatible shapes:
######  [4] vs. [2] [Op:AddV2] 





### Add 2 numpy Array

In [27]:

arr1 = np.array([10,20,30,40,50])
arr2 = np.array([20,40,60,80,100])

sum_arrays = tf.add(arr1, arr2, name = 'Adding_arrays')
print(sum_arrays)

tf.Tensor([ 30  60  90 120 150], shape=(5,), dtype=int32)


### Adding numpy array with scaler

In [30]:
arr1 = np.array([10,20,30,40,50])
# num = 15.5   # apply with same data types for array 
num = 15

add_with_scaler = tf.add(arr1, num)
print(add_with_scaler)

tf.Tensor([25 35 45 55 65], shape=(5,), dtype=int32)


### Add numpy array with single element np array

In [32]:
arr1 = np.array([10,20,30,40,50])
arr2 = ([5])
add = tf.add(arr1,arr2)
add

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([15, 25, 35, 45, 55])>

### Add 2 TF Constant Tensor

In [33]:
const_tensor1 = tf.constant([1,2,3,4])
const_tensor2 = tf.constant([2,3,4,5])

add_constant_tensors = tf.add(const_tensor1, const_tensor2)
print(add_constant_tensors )

tf.Tensor([3 5 7 9], shape=(4,), dtype=int32)


### Add TF Constant Tensor with Scaler

In [34]:
const_tensor1 = tf.constant([1,2,3,4])
x = 20

tf.add(const_tensor1, x)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([21, 22, 23, 24])>

### Add 2 TF Variable

In [35]:
var_tensor1 = tf.Variable([1,2,3,4])
var_tensor2 = tf.Variable([2,4,5,7])

tf.add(var_tensor1, var_tensor2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 3,  6,  8, 11])>

### Add TF Variable with Scaler

In [36]:
var_tensor1 = tf.Variable([1,2,3,4])
x = 15

tf.add(var_tensor1, x)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([16, 17, 18, 19])>

### Add 2 Numpy array with different Shape

In [37]:
x = np.ones(6).reshape(1, 2, 1, 3) # (2,2,3,3)
print("x: ", x)
y = np.ones(6).reshape(2, 1, 3, 1)
print("y: ", y)
 
tf.add(x, y)

x:  [[[[1. 1. 1.]]

  [[1. 1. 1.]]]]
y:  [[[[1.]
   [1.]
   [1.]]]


 [[[1.]
   [1.]
   [1.]]]]


<tf.Tensor: shape=(2, 2, 3, 3), dtype=float64, numpy=
array([[[[2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.]],

        [[2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.]]],


       [[[2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.]],

        [[2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.]]]])>