In [1]:
import tensorflow as tf 
import numpy as np

# Syntax: tf.divide(x, y, name=None)

### Scaler division

In [6]:
a = 10
b = 20
print(" a/b =", a/b)
print(" a/b =", a//b)
 
tf.divide(a,b) 

 a/b = 0.5
 a/b = 0


<tf.Tensor: shape=(), dtype=float64, numpy=0.5>

In [7]:
tf.divide(b, a)

<tf.Tensor: shape=(), dtype=float64, numpy=2.0>

### Divide 2 Numpy Array

In [8]:
npa1 = np.array([1,2,3,4,5])
npa2 = np.array([1,2,3,4,5])
 
tf.divide(npa1, npa2)

<tf.Tensor: shape=(5,), dtype=float64, numpy=array([1., 1., 1., 1., 1.])>

### Divide Numpy array with Scaler

In [9]:
npa1 = np.array([1,2,3,4,5])
a = 10
 
tf.divide(npa1, a)

<tf.Tensor: shape=(5,), dtype=float64, numpy=array([0.1, 0.2, 0.3, 0.4, 0.5])>

### Divide Numpy array with single element np array

In [10]:
npa1 = np.array([1,2,3,4,5])
npa2 = np.array([[1]])
 
tf.divide(npa1, npa2)

<tf.Tensor: shape=(1, 5), dtype=float64, numpy=array([[1., 2., 3., 4., 5.]])>

### Divide 2 TF Constant Tensor

In [11]:
tf_ct1 = tf.constant([1,2,3,4])
tf_ct2 = tf.constant([1,2,3,4])
 
tf.divide(tf_ct1, tf_ct2)

<tf.Tensor: shape=(4,), dtype=float64, numpy=array([1., 1., 1., 1.])>

In [12]:
# Division with operator /
tf_ct1 = tf.constant([1,2,3,4])
tf_ct2 = tf.constant([1,2,3,4])
 
tf_ct1 / tf_ct2

<tf.Tensor: shape=(4,), dtype=float64, numpy=array([1., 1., 1., 1.])>

In [13]:
# Division with operator /
tf_ct1 = tf.constant([1,2,3,4])
tf_ct2 = tf.constant([1,2,3,4])
 
tf_ct1 // tf_ct2

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 1, 1, 1])>

### Divide TF Constant Tensor with Scaler

In [14]:
tf_ct1 = tf.constant([1,2,3,4])
a = 10
tf.divide(tf_ct1, a)

<tf.Tensor: shape=(4,), dtype=float64, numpy=array([0.1, 0.2, 0.3, 0.4])>

In [15]:
# division with operator /
tf_ct1 = tf.constant([1,2,3,4])
a = 10
tf_ct1 / a

<tf.Tensor: shape=(4,), dtype=float64, numpy=array([0.1, 0.2, 0.3, 0.4])>

### Divide 2 TF Variable

In [16]:
tf_vr1 = tf.Variable([1,2,3,4])
tf_vr2 = tf.Variable([1,2,3,4])
 
tf.divide(tf_vr1, tf_vr2)

<tf.Tensor: shape=(4,), dtype=float64, numpy=array([1., 1., 1., 1.])>

# Divide 2 Numpy array with different Shape

In [17]:
x = np.ones(6).reshape(1, 2, 1, 3) # (2,2,3,3)
print("x: ", x)
y = np.ones(6).reshape(2, 1, 3, 1)
print("y: ", y)
 
tf.divide(x, y)

x:  [[[[1. 1. 1.]]

  [[1. 1. 1.]]]]
y:  [[[[1.]
   [1.]
   [1.]]]


 [[[1.]
   [1.]
   [1.]]]]


<tf.Tensor: shape=(2, 2, 3, 3), dtype=float64, numpy=
array([[[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]]])>