In [1]:
# Importing libraries
import tensorflow as tf
import numpy as np

#  Syntax: tf.maximum(x, y, name=None)

##  Get Max value of Scaler

In [2]:
a = 10
b = 20
tf.maximum(a,b)
 
#tf.maximum(a,b).numpy()

<tf.Tensor: shape=(), dtype=int32, numpy=20>

## Get Max Value from 2 List

In [3]:
l1 = [1,2,3,4]
l2 = [5,6,7,8]
 
tf.maximum(l1, l2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([5, 6, 7, 8])>

In [4]:
l1 = [1,2,3,4]
l2 = [5]
 
tf.maximum(l1, l2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([5, 5, 5, 5])>

## Get Max value from 2 tuple

In [5]:
t1 = (1,2,3,4)
t2 = (5,6,7,8)
 
tf.maximum(t1,t2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([5, 6, 7, 8])>

In [6]:
l1 = [1,2,3,4]   # Get Max Value of List/Tuple with Scaler
a =10
tf.maximum(l1, a)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([10, 10, 10, 10])>

## Get Max Value of 2 Numpy Array

In [7]:
npa1 = np.array([1,4,3,9,5])
npa2 = np.array([2,2,3,4,5])
 
tf.maximum(npa1, npa2)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([2, 4, 3, 9, 5])>

## Get Max Value of Numpy array with Scaler

In [8]:
npa1 = np.array([1,2,3,4,5])
a = 3
 
tf.maximum(npa1, a)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([3, 3, 3, 4, 5])>

## Get Max Value of Numpy array with single element np array

In [9]:
npa1 = np.array([1,2,3,4,5])
npa2 = np.array([[2]])
 
tf.maximum(npa1, npa2)

<tf.Tensor: shape=(1, 5), dtype=int32, numpy=array([[2, 2, 3, 4, 5]])>

## Get Max Value of 2 TF Constant Tensor

In [10]:
tf_ct1 = tf.constant([2,2,3,8])
tf_ct2 = tf.constant([3,2,5,4])
 
tf.maximum(tf_ct1, tf_ct2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([3, 2, 5, 8])>

# Get Max Value of 2 TF Variable

In [11]:
tf_vr1 = tf.Variable([2,2,3,8])
tf_vr2 = tf.Variable([3,2,5,4])
 
tf.maximum(tf_vr1, tf_vr2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([3, 2, 5, 8])>

## Get Max Value of TF Variable with Scaler

In [12]:
tf_vr1 = tf.Variable([3,2,5,4])
a = 3
tf.maximum(tf_vr1, a)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([3, 3, 5, 4])>