In [2]:
# Importing libraries
import tensorflow as tf
import numpy as np

#  Syntax: tf.pow(x, y, name=None)

## Power of Scaler

In [3]:
a = 4
b = 2
 
tf.pow(a, b)

<tf.Tensor: shape=(), dtype=int32, numpy=16>

## Power of numpy array

In [4]:
arr1 = np.array([4,9,16], dtype = np.float64)
 
tf.pow(arr1, 2)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 16.,  81., 256.])>

In [5]:
ar1 = np.array([1,2,3], dtype = np.float64)
ar2 = np.array([1,2,3], dtype = np.float64)
 
tf.pow(ar1, ar2)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 1.,  4., 27.])>

In [6]:
y = np.ones(6).reshape(2, 1, 3, 1)*4
print("y : ", y)
tf.pow(y, 2)

y :  [[[[4.]
   [4.]
   [4.]]]


 [[[4.]
   [4.]
   [4.]]]]


<tf.Tensor: shape=(2, 1, 3, 1), dtype=float64, numpy=
array([[[[16.],
         [16.],
         [16.]]],


       [[[16.],
         [16.],
         [16.]]]])>

## Power of Tensor

In [7]:
tf_ct1 = tf.constant([4,9,16], dtype='float')
 
tf.pow(tf_ct1, 3)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([  64.,  729., 4096.], dtype=float32)>

In [8]:
tf_ct1 = tf.constant([4,9,16], dtype='float')
tf_ct2 = tf.constant([3,2,1], dtype='float')
 
tf.pow(tf_ct1, tf_ct2)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([64., 81., 16.], dtype=float32)>

## Power of TF Variable

In [9]:
tf_vr1 = tf.Variable([4,9,16], dtype='half')
 
tf.pow(tf_vr1, 2)

<tf.Tensor: shape=(3,), dtype=float16, numpy=array([ 16.,  81., 256.], dtype=float16)>

In [10]:
tf_vr1 = tf.Variable([4,9,16], dtype='float')
tf_vr2 = tf.Variable([3,2,1], dtype='float')
 
tf.pow(tf_vr1, tf_vr2)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([64., 81., 16.], dtype=float32)>

In [11]:
tf_vr1 = tf.Variable([4,9,16], dtype='float')
tf_vr2 = tf.Variable([3], dtype='float')
 
tf.pow(tf_vr1, tf_vr2)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([  64.,  729., 4096.], dtype=float32)>