In [7]:
# Importing libraries
import tensorflow as tf 
import numpy as np

# Syntax: tf.sqrt(x, name=None)

# Square root of Scalar

In [9]:
a = 25.0
tf.sqrt(a)

<tf.Tensor: shape=(), dtype=float32, numpy=5.0>

## square root of list

In [13]:
ls = [4.0, 9.0, 16.0, 25, 36.0]
tf.sqrt(ls)

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([2., 3., 4., 5., 6.], dtype=float32)>

## Square root of tuple

In [16]:
tpl = (4.0, 9.0, 16.0, 25, 36.0)
tf.sqrt(tpl)

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([2., 3., 4., 5., 6.], dtype=float32)>

## Square root of numpy array 

In [18]:
arr = np.array([4,9,16,25], dtype = np.float64)
tf.sqrt(arr)

<tf.Tensor: shape=(4,), dtype=float64, numpy=array([2., 3., 4., 5.])>

In [19]:
y = np.ones(6).reshape(2, 1, 3, 1)*4
print("Y: " , y)
tf.sqrt(y)

Y:  [[[[4.]
   [4.]
   [4.]]]


 [[[4.]
   [4.]
   [4.]]]]


<tf.Tensor: shape=(2, 1, 3, 1), dtype=float64, numpy=
array([[[[2.],
         [2.],
         [2.]]],


       [[[2.],
         [2.],
         [2.]]]])>

## Square Root of TensorFlow Tensor

In [20]:
	
tf.sqrt(tf.convert_to_tensor(4, dtype='float')) # using scaler value
tf.sqrt(tf.convert_to_tensor([4,9,16], dtype='float')) # using list

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([2., 3., 4.], dtype=float32)>

## Square root of TF constant tensor 

In [21]:
tf_ct1 = tf.constant([4,9,16], dtype='float')
 
tf.sqrt(tf_ct1)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([2., 3., 4.], dtype=float32)>

## Square Root of TF Variable

In [22]:
tf_vr1 = tf.Variable([4,9,16], dtype='half')
 
tf.sqrt(tf_vr1)

<tf.Tensor: shape=(3,), dtype=float16, numpy=array([2., 3., 4.], dtype=float16)>