In [4]:
#  Importing library 

import tensorflow as tf 
import numpy as np 


# Create tensor

In [7]:
a = tf.Variable(10)
a

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=10>

# Get Variable Name, Shape, Data Type & convert into NumpyArray


In [8]:
a.name

'Variable:0'

In [13]:
b= tf.Variable([1,2,3,4], name='my_variable')
b

<tf.Variable 'my_variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4])>

In [14]:
b.shape

TensorShape([4])

In [15]:
b.dtype

tf.int32

In [16]:
# Converting to NumpyArray 

b.numpy()

array([1, 2, 3, 4])

In [17]:
type(b)

tensorflow.python.ops.resource_variable_ops.ResourceVariable


# Create TF using Integer, Float, String, Bool, Complex Number

In [18]:
intVar = tf.Variable([1,2,3])
intVar

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3])>

In [20]:
floatVar = tf.Variable([1.,2.,3.,4,5])
floatVar

<tf.Variable 'Variable:0' shape=(5,) dtype=float32, numpy=array([1., 2., 3., 4., 5.], dtype=float32)>

In [21]:
strVar = tf.Variable("Hello, Everyone!!!")
strVar

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'Hello, Everyone!!!'>

In [23]:
strVar2 = tf.Variable(['A','a','B','b'])
strVar2

<tf.Variable 'Variable:0' shape=(4,) dtype=string, numpy=array([b'A', b'a', b'B', b'b'], dtype=object)>

In [24]:
boolVar = tf.Variable(True)
boolVar

<tf.Variable 'Variable:0' shape=() dtype=bool, numpy=True>

In [25]:
boolVar2 = tf.Variable([True,False,True,False])
boolVar2

<tf.Variable 'Variable:0' shape=(4,) dtype=bool, numpy=array([ True, False,  True, False])>

In [30]:
# Complex number 

# complex =  a+bj

complex_Var = tf.Variable([4+5j])
complex_Var


<tf.Variable 'Variable:0' shape=(1,) dtype=complex128, numpy=array([4.+5.j])>

# Create TF from Constant TensorFlow Variable

In [32]:
tf_constant = tf.constant([1,2,3])
tf_constant

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [34]:
tf.Variable(tf_constant, name = "constant_to_variable")

<tf.Variable 'constant_to_variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3])>

# Create TF variable with different shapes 

In [38]:
arr2D= tf.Variable([[1,2],[3,4]])
arr2D

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [39]:
arr2D.shape

TensorShape([2, 2])

In [41]:
arr3 = tf.Variable([1,2,3,4])
arr3

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4])>

In [44]:
tf.reshape(arr3, (2,2))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

# Get Index of highest value

In [46]:
index= tf.argmax(arr3)
index

<tf.Tensor: shape=(), dtype=int64, numpy=3>

In [47]:
tf.argmax(arr3).numpy()

3

# Viewed/Convert as a tensor

In [48]:
arr3

<tf.Variable 'my_variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4])>

In [49]:
tf.convert_to_tensor(arr3)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4])>

# Change and assign new value to tensor 

In [52]:
boolVal2 = tf.Variable([True, True, False, True], dtype=tf.bool, name='bool_variable')

print(boolVal2)

<tf.Variable 'bool_variable:0' shape=(4,) dtype=bool, numpy=array([ True,  True, False,  True])>


In [54]:
boolVal2.assign([True, False, True, False])
print(boolVal2)

<tf.Variable 'bool_variable:0' shape=(4,) dtype=bool, numpy=array([ True, False,  True, False])>
